[GVF Viewer] New PprzGCS widget to paint GVF parametric trajectories and vector fields
Fabien-B/GcsAgain pull request #15
Opened 2022-08-16 18:37 UTC by jesusBV20

This new PprzGCS tool allows us to paint GVF parametric trajectories and their associated vector fields.

GVF Viewer widget:
- The new GVFViewer widget class was added to the AC_WIDGETS_MAP. This way we can manage the load of the GVF Viewer tool in the layout configuration file. With this new widget, we can configure and visualize some parameters of the GVF trajectory objects. 

- The new "colorbar" basic widget allows GVF Viewer to generate an altitude color bar for GVF parametric trajectories.

- New signals were added to the DispatchetUI in order to build a connection between GVF Viewer, the map widget, and every GVF trajectory object. 
 
GVF trajectory objects and map widget modifications: 
- When a GVF or GVF_PARAMETRIC message is received and the GVF Viewer widget is loaded, the map widget calls "onGVF". This function parses the message, generates the desired GVF trajectory object linked to the AC, and deletes the previous one.

- Every trajectory has a gvf_trajectory class that generates and paints the trajectory points with the telemetry data.

- The new quiver map item allows the gvf_trajectory objects to build the vector field.

- Every point in the path map item now has an associated color. With this modification, the objects of GVF parametric trajectories can change and associate the color of the point with the altitude.

2022-08-16 22:21 UTC, Fabien-B commented
Thank you for this huge work!
If that's OK for you, I would like to wait for September before reviewing this PR.

2022-08-17 09:37 UTC, jesusBV20 commented
> Thank you for this huge work! If that's OK for you, I would like to wait for September before reviewing this PR.

That's ok for me Fabien. I'm not in a hurry :)

2022-09-02 14:55 UTC, Fabien-B commented
Hi @jesusBV20, could you add one of your GVF configuration to paparazzi so I can test it (in simulation at least).
And if there are other things to do, maybe you could write a guide here : https://github.com/paparazzi/paparazzi/tree/master/doc/sphinx/source/user_guide ?
It generates this doc : https://paparazzi-uav.readthedocs.io/

2022-09-02 16:25 UTC, jesusBV20 commented
Okey Fabien, you can test every feature with the user configs that I have just pushed to this branch (I will send a PR to paparazzi, give a moment): https://github.com/UCM-237/paparazzi/tree/gvf_config

In the following days, I will try to write some information about GVF Viewer into the user guide :)

2022-09-02 17:34 UTC, Fabien-B commented
I started to test it, when the drone is in the line_P1_P2 block, the GCS crash at gvf_traj_line.cpp:55, probably an out of bounds error.

2022-09-02 17:55 UTC, jesusBV20 commented
I forgot to mention that you can change the GVF trajectory parameters in the settings. This way you can generate more diverse trajectories.

![image](https://user-images.githubusercontent.com/92217640/188210668-de440ef3-006b-443b-95ae-66267cea7d15.png)

2022-09-19 19:40 UTC, jesusBV20 commented
Hi @Fabien-B! I'm currently working on the GVF Viewer documentation in https://github.com/paparazzi/paparazzi/pull/2896

2022-10-17 07:33 UTC, Fabien-B commented
Hi @jesusBV20 do you had the chance to look at the bug I found above ?
It would be nice to fix it before merging.

2022-10-17 07:43 UTC, jesusBV20 commented
Hi @Fabien-B, I can't see the comment where you mention that bug. However, I have revised my email and I think that you refer to this message: "I started to test it, when the drone is in the line_P1_P2 block, the GCS crash at gvf_traj_line.cpp:55, probably an out of bounds error." Am I right?

2022-10-17 07:57 UTC, Fabien-B commented
Yes, that's it.

2022-10-17 07:59 UTC, jesusBV20 commented
Okey, I'll try to fix it. sorry for the inconvenience, I didn't see that message.

2022-10-17 13:33 UTC, jesusBV20 commented
Did you test the GVF Viewer with the changes in the GVF firmware (https://github.com/paparazzi/paparazzi/pull/2893)??

2022-10-19 17:24 UTC, jesusBV20 commented
The out-of-bounds error should be fixed with this simple change. Please, feel free to make suggestions related to code optimization/comprehension. Let me know if you want me to make any other changes.

2022-10-27 16:25 UTC, Fabien-B requested changes
The previous bugs are fixed, but there is an other: 
On exiting the app actually crash (with code 11 on my side).
The same thing happen when trying to remove an aircraft : Aicrafts-> gvf_sonic2 -> Remove

2022-10-28 13:16 UTC, jesusBV20 commented
Ooh okey. I'll take a look.

2022-10-29 21:19 UTC, jesusBV20 commented
The bug should be fixed!

2022-11-02 09:26 UTC, merged